### ISSUE TITLE
Gems

### ISSUE THREAD

**Issue by BalintXHD** [Akrivus/Amalgam#12]
Melanite texture shows incorrect

![2018-12-25_17 49 21](https://user-images.githubusercontent.com/36235183/50425458-e99c2b80-0876-11e9-81ff-cae510c93540.png)

Nacre's hat glitching in the head

![2018-12-25_18 09 26](https://user-images.githubusercontent.com/36235183/50425462-0e909e80-0877-11e9-86e4-bd82f6182dc5.png)

Okay now this isn't really a problem it's just bugs me

![2018-12-25_17 49 28](https://user-images.githubusercontent.com/36235183/50425476-32ec7b00-0877-11e9-8651-2d18c5a21e46.png)

**Comment by Akrivus** [comment]
These can't be fixed, I didn't add them, I don't even celebrate Christmas.
