### ISSUE TITLE
I need help with downloading Amalgam

### ISSUE THREAD

**Issue by Virtualaxx** [Akrivus/Amalgam#13]
Whenever I try to do the clone command it gives me this:
![github](https://user-images.githubusercontent.com/47789312/53042065-57cb2c00-347d-11e9-8595-2d4f45736693.PNG)

Also, I am very new to programming so I have no clue what to do now .-.
Please help when you can.

Thanks 👍

**Comment by Virtualaxx** [comment]
The ipconfig thing was just to see if it was like command prompt
I should probably blur it out because I'm probably getting Ddossed.

**Comment by Akrivus** [comment]
You don't have the gradle wrapper in your home directory. You'll need to run `cd Amalgam` and then retry the `./gradlew setupDecompWorkspace` command again.

**Comment by Virtualaxx** [comment]
Is the fatal thing supposed to happen?

**Comment by Akrivus** [comment]
Refer [to this StackOverflow question.](https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining)

**Comment by Virtualaxx** [comment]
should i replace large-repository into the link?

**Comment by Virtualaxx** [comment]
Nevermind I read it.

Thanks a lot for the help!!

**Comment by Akrivus** [comment]
No problem! If you have any issues feel free to open a new issue. :smile:

**Comment by Virtualaxx** [comment]
What do I do after this. (Sorry for being such a bother i'm a noob at coding as you can see)
![capture](https://user-images.githubusercontent.com/47789312/53044269-6ec04d00-3482-11e9-9a83-31b65b8ce674.PNG)

**Comment by Virtualaxx** [comment]
Also please simplify  it because i don't understand things like repository.

**Comment by Akrivus** [comment]
If you can't understand what a repository is, despite being on a repository right now, I'd highly suggest you research Git and recommend learning about the Forge MDK and Java if you haven't already.

* [https://www.atlassian.com/git/tutorials/what-is-git](What is Git?)
* [https://www.youtube.com/watch?v=rmWBP5ifDlw](Minecraft 1.12.2: Modding Tutorial - Workspace Setup (#1))
* [https://www.learnjavaonline.org/](Learn Java - Free Interactive Java Tutorial)

**Comment by Virtualaxx** [comment]
Okay thanks. I think you can close this issue for real now. 😆

**Comment by Virtualaxx** [comment]
AHHHH IM SO STUPID THIS WHOLE TIME I JUST HAD TO PUT THE JAR FILE IN THE MODS FOLDER LIKE MY TEACHER SAID!! I MISREAD IT AND IT TOOK ME OVER A WEEK TO REALIZE 😭
