### ISSUE TITLE
The Mobile Injector is drunk

### ISSUE THREAD

**Issue by BalintXHD** [Akrivus/Amalgam#2]
the injector is drunk, just look at it

![2018-12-10_15 15 14](https://user-images.githubusercontent.com/36235183/49737996-8f07aa80-fc8e-11e8-9709-c965fa50516c.png)

Why is it planting seeds there?

**Comment by Akrivus** [comment]
Resolved with 7db0f1a831062f69c553990cd2ae62a4b40f9aa8.
