### ISSUE TITLE
Bubbles

### ISSUE THREAD

**Issue by BalintXHD** [Akrivus/Amalgam#3]
the bubbles are duplicating items
![2018-12-10_15 08 32](https://user-images.githubusercontent.com/36235183/49737570-85ca0e00-fc8d-11e8-9001-e99a00c58f1c.png)
![2018-12-10_15 08 38](https://user-images.githubusercontent.com/36235183/49737572-85ca0e00-fc8d-11e8-871f-0313629561b7.png)
![2018-12-10_15 08 41](https://user-images.githubusercontent.com/36235183/49737573-8662a480-fc8d-11e8-9320-91564e95bce5.png)

**Comment by Akrivus** [comment]
Fixed in 98a4ba44217f30b05f02713ccefb5fef4d7651a1.
