### ISSUE TITLE
Injector seed problem

### ISSUE THREAD

**Issue by BalintXHD** [Akrivus/Amalgam#5]
this
![2018-12-10_18 59 44](https://user-images.githubusercontent.com/36235183/49751689-58da2300-fcae-11e8-9402-d70ab53b5c8c.png)
![2018-12-10_18 59 48](https://user-images.githubusercontent.com/36235183/49751691-5972b980-fcae-11e8-8f5c-511769ad1ac8.png)
![2018-12-10_18 59 53](https://user-images.githubusercontent.com/36235183/49751693-5972b980-fcae-11e8-8ae5-04c0826e32ce.png)
![2018-12-10_18 59 55](https://user-images.githubusercontent.com/36235183/49751694-5972b980-fcae-11e8-8cab-b4b45cb588fd.png)

**Comment by Akrivus** [comment]
Fixed in e288b2b312b902367ab254901352667d87c9760b.
